# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c5e3ed9501ca5e91a471872847d71beea1904587a0cfcf0514590b9f5452112413dda738c9f9575f6f7ab0f18cdadfcd54d8512d522128ce210e4c2d5b807a8

test:
  secret_key_base: f7a9bf4170d1c69aea20d758057eb92fc146f1abe067ebdfa08a093c9acfacd95ffaaa74f98344248d52ba5cd57f3c131e1d265abdec537252b3c8fe9ee68338

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
